name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
    - uses: cachix/cachix-action@v14
      with:
        name: intransience
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix flake check
